using Build;
using Cake.Common.Build.GitHubActions;
using Cake.Common.Build;
using Cake.Core;
using Cake.Core.Diagnostics;
using Cake.Core.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System.Text;
using System.Diagnostics;

namespace Tests
{
    [TestClass]
    public class UpdateVersionTaskTests
    {
        private const string SAMPLE_ISS_CONTENT = """
        ; Script generated by the Inno Setup Script Wizard.
        ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

        #define MyAppName "Product Manager for DAZ Studio"
        #define MyAppVersion "0.9.8"
        #define MyAppPublisher "Solomon Blount"
        #define MyAppURL "https://www.thesolomonchronicles.com"
        #define MyAppExeName "DAZ_Installer.Windows.exe"

        [Setup]
        ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
        ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
        AppId={{0F0CE93C-AAF3-499C-B35A-4705D6268F98}
        AppName={#MyAppName}
        AppVersion={#MyAppVersion}
        ;AppVerName={#MyAppName} {#MyAppVersion}
        AppPublisher={#MyAppPublisher}
        AppPublisherURL={#MyAppURL}
        AppSupportURL={#MyAppURL}
        AppUpdatesURL={#MyAppURL}
        DefaultDirName={autopf}\{#MyAppName}
        """;

        private const string SAMPLE_CSPROJ_CONTENT = """
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net6.0-windows</TargetFramework>
            <Version>$(AssemblyVersion)$(VersionSuffix)</Version>
            <FileVersion>0.9.8</FileVersion>
            <AssemblyVersion>0.9.8</AssemblyVersion>
          </PropertyGroup>
          <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
            <VersionSuffix>Pre-alpha</VersionSuffix>
          </PropertyGroup>
        </Project>
        """;

        private const string SAMPLE_VERSION_CONTENT = "0.9.8\nPre-alpha";

        private static Mock<IFile> SetupFile(string content, out MemoryStream stream)
        {
            var mockFile = new Mock<IFile>();
            stream = new MemoryStream(ushort.MaxValue);
            var readStream = new MemoryStream(Encoding.UTF8.GetBytes(content));
            mockFile.Setup(x => x.Exists).Returns(true);
            mockFile.Setup(x => x.Length).Returns(100); // Assuming file size is within limits
            mockFile.Setup(x => x.Open(FileMode.OpenOrCreate, FileAccess.Write, FileShare.Write)).Returns(stream);
            mockFile.Setup(x => x.Open(FileMode.Open, FileAccess.Read, FileShare.Read)).Returns(readStream);
            return mockFile;
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha")]
        public async Task RunAsync_ShouldUpdateVersionsCorrectly(string version, string suffix)
        {

            // Arrange
            var context = Mock.Of<ICakeContext>();
            var mockCakeContext = Mock.Get(context);
            var mockFileSystem = new Mock<IFileSystem>();
            var mockPathFinder = new Mock<IPathFinder>();
            var mockGitHubActions = new Mock<IGitHubActionsProvider>();
            var mockEnvironment = new Mock<ICakeEnvironment>();
            var mockArguments = new Mock<ICakeArguments>();
            
            mockCakeContext.SetupGet(x => x.Environment).Returns(mockEnvironment.Object);
            mockEnvironment.SetupGet(x => x.WorkingDirectory).Returns(new DirectoryPath("O:/DAZ_Installer"));
            mockCakeContext.SetupGet(x => x.Arguments).Returns(mockArguments.Object);
            mockArguments.Setup(x => x.HasArgument(It.IsAny<string>())).Returns(false);
            mockGitHubActions.SetupGet(x => x.IsRunningOnGitHubActions).Returns(true);


            var buildContext = new BuildContext(context)
            {
                FileSystem = mockFileSystem.Object,
                PathFinder = mockPathFinder.Object,
                GithubActions = mockGitHubActions.Object,
            };

            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.WINDOWS_PROJECT_PATH)).Returns(BuildContext.WINDOWS_PROJECT_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.INSTALLER_ISS_PATH)).Returns(BuildContext.INSTALLER_ISS_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.VERSION_FILE_PATH)).Returns(BuildContext.VERSION_FILENAME);

            var mockProjectFile = SetupFile(SAMPLE_CSPROJ_CONTENT, out var projectStream);
            var mockInstallerFile = SetupFile(SAMPLE_ISS_CONTENT, out var installerStream);
            var mockVersionFile = SetupFile(SAMPLE_VERSION_CONTENT, out var versionStream);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.WINDOWS_PROJECT_FILENAME)).Returns(mockProjectFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.INSTALLER_ISS_FILENAME)).Returns(mockInstallerFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.VERSION_FILENAME)).Returns(mockVersionFile.Object);

            var task = new UpdateVersionTask();

            // Act
            await task.RunAsync(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(version, buildContext.Version);
            Assert.AreEqual(suffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.
            var projectContent = Encoding.UTF8.GetString(projectStream.ToArray());
            var installerContent = Encoding.UTF8.GetString(installerStream.ToArray());
            var versionContent = Encoding.UTF8.GetString(versionStream.ToArray());

            StringAssert.Contains(projectContent, $"<FileVersion>{version}</FileVersion>");
            StringAssert.Contains(projectContent, $"<AssemblyVersion>{version}</AssemblyVersion>");
            StringAssert.Contains(projectContent, $"<VersionSuffix>{suffix}</VersionSuffix>");

            StringAssert.Contains(installerContent, $"#define MyAppVersion \"{version}\"");

            Assert.AreEqual($"{version}\n{suffix}", versionContent);

            Debug.WriteLine("Got the following project content:");
            Debug.WriteLine(projectContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following installer content:");
            Debug.WriteLine(installerContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following version content:");
            Debug.WriteLine(versionContent);
            Debug.WriteLine("");
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha", "0.9.10")]
        [DataRow("0.9.9", "", "0.9.10")]
        [DataRow("10.11.0", "Beta", "10.11.1")]
        public async Task RunAsync_DifferentInitValues_ShouldUpdateVersionsCorrectly(string version, string suffix, string expectedVersion)
        {

            // Arrange
            var context = Mock.Of<ICakeContext>();
            var mockCakeContext = Mock.Get(context);
            var mockFileSystem = new Mock<IFileSystem>();
            var mockPathFinder = new Mock<IPathFinder>();
            var mockGitHubActions = new Mock<IGitHubActionsProvider>();
            var mockEnvironment = new Mock<ICakeEnvironment>();
            var mockArguments = new Mock<ICakeArguments>();

            mockCakeContext.SetupGet(x => x.Environment).Returns(mockEnvironment.Object);
            mockEnvironment.SetupGet(x => x.WorkingDirectory).Returns(new DirectoryPath("O:/DAZ_Installer"));
            mockCakeContext.SetupGet(x => x.Arguments).Returns(mockArguments.Object);
            mockArguments.Setup(x => x.HasArgument(It.IsAny<string>())).Returns(false);
            mockGitHubActions.SetupGet(x => x.IsRunningOnGitHubActions).Returns(true);


            var buildContext = new BuildContext(context)
            {
                FileSystem = mockFileSystem.Object,
                PathFinder = mockPathFinder.Object,
                GithubActions = mockGitHubActions.Object,
            };

            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.WINDOWS_PROJECT_PATH)).Returns(BuildContext.WINDOWS_PROJECT_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.INSTALLER_ISS_PATH)).Returns(BuildContext.INSTALLER_ISS_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.VERSION_FILE_PATH)).Returns(BuildContext.VERSION_FILENAME);

            var mockProjectFile = SetupFile(SAMPLE_CSPROJ_CONTENT, out var projectStream);
            var mockInstallerFile = SetupFile(SAMPLE_ISS_CONTENT, out var installerStream);
            var mockVersionFile = SetupFile($"{version}\n{suffix}", out var versionStream);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.WINDOWS_PROJECT_FILENAME)).Returns(mockProjectFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.INSTALLER_ISS_FILENAME)).Returns(mockInstallerFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.VERSION_FILENAME)).Returns(mockVersionFile.Object);

            var task = new UpdateVersionTask();

            // Act
            await task.RunAsync(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(expectedVersion, buildContext.Version);
            Assert.AreEqual(suffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.
            var projectContent = Encoding.UTF8.GetString(projectStream.ToArray());
            var installerContent = Encoding.UTF8.GetString(installerStream.ToArray());
            var versionContent = Encoding.UTF8.GetString(versionStream.ToArray());

            StringAssert.Contains(projectContent, $"<FileVersion>{expectedVersion}</FileVersion>");
            StringAssert.Contains(projectContent, $"<AssemblyVersion>{expectedVersion}</AssemblyVersion>");
            StringAssert.Contains(projectContent, $"<VersionSuffix>{suffix}</VersionSuffix>");

            StringAssert.Contains(installerContent, $"#define MyAppVersion \"{expectedVersion}\"");

            var expectedVersionContent = $"{expectedVersion}\n{suffix}";
            Assert.AreEqual(expectedVersionContent, versionContent);

            Debug.WriteLine("Got the following project content:");
            Debug.WriteLine(projectContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following installer content:");
            Debug.WriteLine(installerContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following version content:");
            Debug.WriteLine(versionContent);
            Debug.WriteLine("");
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha")]
        [DataRow("0.9.9", "")]
        [DataRow("20.987.6543", "Beta")]
        public async Task RunAsync_Override_ShouldUpdateVersionsCorrectly(string version, string suffix)
        {

            // Arrange
            var context = Mock.Of<ICakeContext>();
            var mockCakeContext = Mock.Get(context);
            var mockFileSystem = new Mock<IFileSystem>();
            var mockPathFinder = new Mock<IPathFinder>();
            var mockGitHubActions = new Mock<IGitHubActionsProvider>();
            var mockEnvironment = new Mock<ICakeEnvironment>();
            var mockArguments = new Mock<ICakeArguments>();

            mockCakeContext.SetupGet(x => x.Environment).Returns(mockEnvironment.Object);
            mockEnvironment.SetupGet(x => x.WorkingDirectory).Returns(new DirectoryPath("O:/DAZ_Installer"));
            mockCakeContext.SetupGet(x => x.Arguments).Returns(mockArguments.Object);
            mockArguments.Setup(x => x.HasArgument(It.IsAny<string>())).Returns(false);
            mockGitHubActions.SetupGet(x => x.IsRunningOnGitHubActions).Returns(true);


            var buildContext = new BuildContext(context)
            {
                FileSystem = mockFileSystem.Object,
                PathFinder = mockPathFinder.Object,
                GithubActions = mockGitHubActions.Object,
                Version = version,
                VersionSuffix = suffix,
                VersionOverriden = true,
            };

            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.WINDOWS_PROJECT_PATH)).Returns(BuildContext.WINDOWS_PROJECT_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.INSTALLER_ISS_PATH)).Returns(BuildContext.INSTALLER_ISS_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.VERSION_FILE_PATH)).Returns(BuildContext.VERSION_FILENAME);

            var mockProjectFile = SetupFile(SAMPLE_CSPROJ_CONTENT, out var projectStream);
            var mockInstallerFile = SetupFile(SAMPLE_ISS_CONTENT, out var installerStream);
            var mockVersionFile = SetupFile(SAMPLE_VERSION_CONTENT, out var versionStream);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.WINDOWS_PROJECT_FILENAME)).Returns(mockProjectFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.INSTALLER_ISS_FILENAME)).Returns(mockInstallerFile.Object);
            mockFileSystem.Setup(x => x.GetFile(BuildContext.VERSION_FILENAME)).Returns(mockVersionFile.Object);

            var task = new UpdateVersionTask();

            // Act
            await task.RunAsync(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(version, buildContext.Version);
            Assert.AreEqual(suffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.
            var projectContent = Encoding.UTF8.GetString(projectStream.ToArray());
            var installerContent = Encoding.UTF8.GetString(installerStream.ToArray());
            var versionContent = Encoding.UTF8.GetString(versionStream.ToArray());

            StringAssert.Contains(projectContent, $"<FileVersion>{version}</FileVersion>");
            StringAssert.Contains(projectContent, $"<AssemblyVersion>{version}</AssemblyVersion>");
            StringAssert.Contains(projectContent, $"<VersionSuffix>{suffix}</VersionSuffix>");

            StringAssert.Contains(installerContent, $"#define MyAppVersion \"{version}\"");

            Assert.AreEqual($"{version}\n{suffix}", versionContent);

            Debug.WriteLine("Got the following project content:");
            Debug.WriteLine(projectContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following installer content:");
            Debug.WriteLine(installerContent);
            Debug.WriteLine("");
            Debug.WriteLine("Got the following version content:");
            Debug.WriteLine(versionContent);
            Debug.WriteLine("");
        }
    }
}