using Build;
using Cake.Common.Build.GitHubActions;
using Cake.Common.Build;
using Cake.Core;
using Cake.Core.Diagnostics;
using Cake.Core.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System.Text;
using System.Diagnostics;
using System.Threading.Tasks;
using System;

namespace Build.Tests
{
    [TestClass]
    public class UpdateVersionTaskTests
    {
        private const string SAMPLE_ISS_CONTENT = """
        ; Script generated by the Inno Setup Script Wizard.
        ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

        #define MyAppName "Product Manager for DAZ Studio"
        #define MyAppVersion "0.9.8"
        #define MyAppPublisher "Solomon Blount"
        #define MyAppURL "https://www.thesolomonchronicles.com"
        #define MyAppExeName "DAZ_Installer.Windows.exe"

        [Setup]
        ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
        ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
        AppId={{0F0CE93C-AAF3-499C-B35A-4705D6268F98}
        AppName={#MyAppName}
        AppVersion={#MyAppVersion}
        ;AppVerName={#MyAppName} {#MyAppVersion}
        AppPublisher={#MyAppPublisher}
        AppPublisherURL={#MyAppURL}
        AppSupportURL={#MyAppURL}
        AppUpdatesURL={#MyAppURL}
        DefaultDirName={autopf}\{#MyAppName}
        """;

        private const string SAMPLE_CSPROJ_CONTENT = """
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>WinExe</OutputType>
            <TargetFramework>net6.0-windows</TargetFramework>
            <Version>$(AssemblyVersion)$(VersionSuffix)</Version>
            <FileVersion>0.9.8</FileVersion>
            <AssemblyVersion>0.9.8</AssemblyVersion>
          </PropertyGroup>
          <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
            <VersionSuffix>Pre-alpha</VersionSuffix>
          </PropertyGroup>
        </Project>
        """;

        private const string SAMPLE_VERSION_CONTENT = "0.9.8\nPre-alpha";

        private Mock<ICakeContext> mockCakeContext = null!;
        private Mock<IFileSystem> mockFileSystem = null!;
        private Mock<IPathFinder> mockPathFinder = null!;
        private Mock<IGitHubActionsProvider> mockGitHubActions = null!;
        private BuildContext buildContext = null!;
        private Dictionary<string, MemoryStream> fileStreams = null!;

        [TestInitialize]
        public void TestInitialize()
        {
            var context = Mock.Of<ICakeContext>();
            mockCakeContext = Mock.Get(context);
            mockFileSystem = new Mock<IFileSystem>();
            mockPathFinder = new Mock<IPathFinder>();
            mockGitHubActions = new Mock<IGitHubActionsProvider>();
            var mockEnvironment = new Mock<ICakeEnvironment>();
            var mockArguments = new Mock<ICakeArguments>();
            fileStreams = new Dictionary<string, MemoryStream>();

            mockCakeContext.SetupGet(x => x.Environment).Returns(mockEnvironment.Object);
            mockEnvironment.SetupGet(x => x.WorkingDirectory).Returns(new DirectoryPath("O:/DAZ_Installer"));
            mockCakeContext.SetupGet(x => x.Arguments).Returns(mockArguments.Object);
            mockArguments.Setup(x => x.HasArgument(It.IsAny<string>())).Returns(false);
            mockGitHubActions.SetupGet(x => x.IsRunningOnGitHubActions).Returns(true);

            buildContext = new BuildContext(context)
            {
                FileSystem = mockFileSystem.Object,
                PathFinder = mockPathFinder.Object,
                GithubActions = mockGitHubActions.Object,
            };

            SetupMockFiles();
        }

        private void SetupMockFiles()
        {
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.WINDOWS_PROJECT_PATH)).Returns(BuildContext.WINDOWS_PROJECT_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.INSTALLER_ISS_PATH)).Returns(BuildContext.INSTALLER_ISS_FILENAME);
            mockPathFinder.Setup(x => x.FindPath(UpdateVersionTask.VERSION_FILE_PATH)).Returns(BuildContext.VERSION_FILENAME);

            SetupMockFile(BuildContext.WINDOWS_PROJECT_FILENAME, SAMPLE_CSPROJ_CONTENT);
            SetupMockFile(BuildContext.INSTALLER_ISS_FILENAME, SAMPLE_ISS_CONTENT);
            SetupMockFile(BuildContext.VERSION_FILENAME, SAMPLE_VERSION_CONTENT);
        }

        private void SetupMockFile(string filename, string content)
        {
            var mockFile = new Mock<IFile>();
            var stream = new MemoryStream(ushort.MaxValue);
            var writer = new StreamWriter(stream);
            writer.Write(content);
            writer.Flush();
            stream.Position = 0;

            fileStreams[filename] = stream;

            mockFile.Setup(x => x.Exists).Returns(true);
            mockFile.Setup(x => x.Length).Returns(100); // Assuming file size is within limits
            mockFile.Setup(x => x.Open(FileMode.OpenOrCreate, FileAccess.Write, FileShare.Write))
                    .Returns(() =>
                    {
                        fileStreams[filename].SetLength(0);
                        return fileStreams[filename];
                    });
            mockFile.Setup(x => x.Open(FileMode.Open, FileAccess.Read, FileShare.Read))
                    .Returns(() => new MemoryStream(fileStreams[filename].ToArray()));

            mockFileSystem.Setup(x => x.GetFile(filename)).Returns(mockFile.Object);
        }
        private void VerifyFileContents(string filename, string expectedVersion, string? expectedSuffix = null)
        {
            var file = mockFileSystem.Object.GetFile(filename);
            var stream = file.OpenRead();
            var reader = new StreamReader(stream);
            var content = reader.ReadToEnd();

            if (filename == BuildContext.WINDOWS_PROJECT_FILENAME)
            {
                StringAssert.Contains(content, $"<FileVersion>{expectedVersion}</FileVersion>");
                StringAssert.Contains(content, $"<AssemblyVersion>{expectedVersion}</AssemblyVersion>");
                if (expectedSuffix != null)
                {
                    StringAssert.Contains(content, $"<VersionSuffix>{expectedSuffix}</VersionSuffix>");
                }
            }
            else if (filename == BuildContext.INSTALLER_ISS_FILENAME)
            {
                StringAssert.Contains(content, $"#define MyAppVersion \"{expectedVersion}\"");
            }
            else if (filename == BuildContext.VERSION_FILENAME)
            {
                var expectedContent = expectedVersion + (string.IsNullOrEmpty(expectedSuffix) ? "" : "\n" + expectedSuffix);
                Assert.AreEqual(expectedContent, content.Trim());
            }

            Debug.WriteLine($"Content of {filename}:");
            Debug.WriteLine(content);
            Debug.WriteLine("");
        }

        [TestMethod]
        public void RunAsyncNoVersion()
        {
            // Arrange
            mockCakeContext.Setup(x => x.Arguments.HasArgument("no-version")).Returns(true);
            var task = new UpdateVersionTask();

            // Act
            task.Run(buildContext);

            // Assert
            mockGitHubActions.VerifyNoOtherCalls();
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha")]
        public void RunAsync_ShouldUpdateVersionsCorrectly(string expectedVersion, string expectedSuffix)
        {

            // Arrange
            var task = new UpdateVersionTask();

            // Act
            task.Run(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(expectedVersion, buildContext.Version);
            Assert.AreEqual(expectedSuffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.
            VerifyFileContents(BuildContext.WINDOWS_PROJECT_FILENAME, expectedVersion, expectedSuffix);
            VerifyFileContents(BuildContext.INSTALLER_ISS_FILENAME, expectedVersion);
            VerifyFileContents(BuildContext.VERSION_FILENAME, expectedVersion, expectedSuffix);
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha", "0.9.10")]
        [DataRow("0.9.9", "", "0.9.10")]
        [DataRow("10.11.0", "Beta", "10.11.1")]
        public void RunAsync_DifferentInitValues_ShouldUpdateVersionsCorrectly(string initialVersion, string initialSuffix, string expectedVersion)
        {

            // Arrange
            SetupMockFile(BuildContext.VERSION_FILENAME, $"{initialVersion}\n{initialSuffix}");
            var task = new UpdateVersionTask();

            // Act
            task.Run(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(expectedVersion, buildContext.Version);
            Assert.AreEqual(initialSuffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.
            VerifyFileContents(BuildContext.WINDOWS_PROJECT_FILENAME, expectedVersion, initialSuffix);
            VerifyFileContents(BuildContext.INSTALLER_ISS_FILENAME, expectedVersion);
            VerifyFileContents(BuildContext.VERSION_FILENAME, expectedVersion, initialSuffix);
        }

        [TestMethod]
        [DataRow("0.9.9", "Pre-alpha")]
        [DataRow("0.9.9", "")]
        [DataRow("20.987.6543", "Beta")]
        public void RunAsync_Override_ShouldUpdateVersionsCorrectly(string version, string suffix)
        {

            // Arrange
            buildContext.Version = version;
            buildContext.VersionSuffix = suffix;
            buildContext.VersionOverriden = true;
            var task = new UpdateVersionTask();

            // Act
            task.Run(buildContext);

            // Assert

            // Verify that the version was incremented
            Assert.AreEqual(version, buildContext.Version);
            Assert.AreEqual(suffix, buildContext.VersionSuffix);

            // Verify that the files were indeed updated.

            VerifyFileContents(BuildContext.WINDOWS_PROJECT_FILENAME, version, suffix);
            VerifyFileContents(BuildContext.INSTALLER_ISS_FILENAME, version);
            VerifyFileContents(BuildContext.VERSION_FILENAME, version, suffix);
        }
    }
}